#ifndef FLEXTRUM_TYPES_H_
#define FLEXTRUM_TYPES_H_

#ifdef __cplusplus
extern "C"{
#endif


//TODO currently mapped 1 to 1 with flex_action_type_t
typedef enum{
ACTION_FORWARD 	,
ACTION_TRAP 	,
ACTION_COUNTER 	,
ACTION_MIRROR 	,
ACTION_POLICER 	,
ACTION_SET_PRIO ,	
ACTION_SET_VLAN ,	
ACTION_SET_INNER_VLAN_PRI 	,
ACTION_SET_OUTER_VLAN_PRI 	,
ACTION_SET_INNER_VLAN_ID 	,
ACTION_SET_OUTER_VLAN_ID 	,
ACTION_SET_SRC_MAC 	,
ACTION_SET_DST_MAC 	,
ACTION_SET_DSCP 	,
ACTION_SET_BRIDGE 	,
ACTION_PBS 	,
ACTION_SET_TC, 	
ACTION_SET_TTL, 	
ACTION_DEC_TTL ,	
ACTION_SET_COLOR, 	
ACTION_SET_ECN 	,
ACTION_SET_USER_TOKEN 	,
ACTION_DONT_LEARN 	,
ACTION_RPF 	,
ACTION_MC_ROUTE 	,
ACTION_TUNNEL_DECAP ,	
ACTION_GOTO 	,
ACTION_SET_ROUTER 	,
ACTION_MC 	,
ACTION_UC_ROUTE 	,
ACTION_SET_DSCP_REWRITE 	,
ACTION_SET_PCP_REWRITE 	,
ACTION_EGRESS_MIRROR 	,
ACTION_IGNORE_EGRESS_VLAN_FILTER 	,
ACTION_IGNORE_EGRESS_STP_FILTER 	,
ACTION_DISABLE_OVERLAY_LEARNING 	,
ACTION_PORT_FILTER 	,
ACTION_SET_MPLS_TTL ,	
ACTION_DEC_MPLS_TTL ,	
ACTION_SET_EXP 	,
ACTION_SET_EXP_REWRITE 	,
ACTION_PBILM 	,
FLEX_ACTION_TYPE_LAST 	,
FLEX_ACTION_TYPE_MIN 	,
FLEX_ACTION_TYPE_MAX 	,
ACTION_INVALID,
} flextrum_action_type_t;



#ifdef __cplusplus
}
#endif

#endif