/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "switch_sai_constants.h"

namespace switch_sai {

const switch_saiConstants g_switch_sai_constants;

switch_saiConstants::switch_saiConstants() {
}

} // namespace

