/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef switch_sai_CONSTANTS_H
#define switch_sai_CONSTANTS_H

#include "switch_sai_types.h"

namespace switch_sai {

class switch_saiConstants {
 public:
  switch_saiConstants();

};

extern const switch_saiConstants g_switch_sai_constants;

} // namespace

#endif
