Document: p4-sai-adapter
Title: Debian p4-sai-adapter Manual
Author: <insert document author here>
Abstract: This manual describes what p4-sai-adapter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/p4-sai-adapter/p4-sai-adapter.sgml.gz

Format: postscript
Files: /usr/share/doc/p4-sai-adapter/p4-sai-adapter.ps.gz

Format: text
Files: /usr/share/doc/p4-sai-adapter/p4-sai-adapter.text.gz

Format: HTML
Index: /usr/share/doc/p4-sai-adapter/html/index.html
Files: /usr/share/doc/p4-sai-adapter/html/*.html
